spring.application.name=backend

spring.datasource.url=jdbc:postgresql://ep-sweet-hall-at4d6xzg.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_JnX7whNU6VzR

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}